name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      MAVEN_OPTS: -Xmx2048m -XX:+TieredCompilation -XX:TieredStopAtLevel=1

    steps:
    - uses: actions/checkout@v4

    - name: Clean Maven cache
      run: rm -rf ~/.m2/repository

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.11'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B -U clean compile
